graph TD
    A[Upstream Commit] -->|check suitability| B(Run a downstream rebase to get the latest changes)
    B --> C{Run in<br> Parallel}
    C -->|Appveyor CI| D[fa:fa-desktop <br>Windows]
    C -->|Circle CI| E[fa:fa-desktop <br>Docker]
    C -->|Cirrus CI| F[fa:fa-desktop <br>FreeBSD]
    C -->|Azure DevOPS| H[fa:fa-desktop <br>Fuzzing Test<br>+<br>Inspect Deploy<br>Package]
    H[fa:fa-desktop <br>Fuzzing Test<br>+<br>Inspection of<br> Deployment<br>Package] -->|manual approval| X(Azure Deploys<br>the Release)
    C -..->|Decommissioned| G[fa:fa-desktop <br>TravisCI]



graph TD
    A[Packaging] -->|Is CI ok?| B(<br>Manual Startup<br>...)
    B --> B1[Get Source Code<br>From Upstream]
    B1 --> C{Providers}
    C -->|GitLab CI| D[fa:fa-desktop <br>FlatPak]
    C -->|Launchpad| E[fa:fa-desktop <br>Snap]
    C -->|GitHub Actions| F[fa:fa-desktop <br>Docker<br>Image]
    C -->|Azure DevOPS| H[fa:fa-desktop <br>Windows<br>64bit]
    C -->|experimental<br>Bitrise Mobile DevOps| K[fa:fa-desktop <br>Android<br>ARM e X86<br><i><u>no package</u></i>]
    C -->|experimental<br>CircleCI| L[fa:fa-desktop <br>Solaris 11.4<br>64bit<br><i><u>no package</u></i>]
