######################################################################
# Copyright (c) 2021 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################

---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: Transfer the script
      copy: src=../build-john.sh dest=/home/ubuntu/build-john.sh mode=0777

    - name: Execute the script
      shell: /home/ubuntu/build-john.sh | tee buildlog.txt
