######################################################################
# Copyright (c) 2021 Claudio André <claudioandre.br at gmail.com>
#
# This program comes with ABSOLUTELY NO WARRANTY; express or implied.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, as expressed in version 2, seen at
# http://www.gnu.org/licenses/gpl-2.0.html
######################################################################

---
- hosts: all
  remote_user: ubuntu
  tasks:
     - name: Copy a file called 'hashes.txt' to all requested remote servers.
       copy:
         src: ../hashes.txt
         dest: /home/ubuntu/hashes.txt
         owner: ubuntu
         group: ubuntu
         mode: '0644'
